FROM alpine:latest

RUN mkdir -p /API

WORKDIR /API

COPY . /API

RUN apk add --update nodejs npm \
	&& apk add --no-cache bash \
	&& apk --update add postgresql-client \
	&& npm install

CMD [ "npm", "start" ]
